### ISSUE TITLE
treadle.executable.TreadleException when ModelCheckFail

### ISSUE THREAD

**Issue by liuyic00** [ucb-bar/chisel-testers2#460]
There is a `treadle.executable.TreadleException` when I run the `verify` and fail the verify.  

I minimized the problem:  
`CheckerA` throws an exception `treadle.executable.TreadleException: setValue: Cannot find regFile1__GEN_8_invalid in symbol table` when fail the verify.  
`CheckerB` fail the verify and printed error message correctly, as a contrast.  
Both checkers have the same function, but `CheckerA` implement by submodules.

``` log
...
Error: poke(regFile1__GEN_8_invalid, 0)
Writing snapshot file test_run_dir/CheckerA_should_pass/CheckerA.datastore.snapshot.json
Assertion failed
    at RegFileSpec.scala:46 assert(reg1(io.rd.idx) =/= reg2(io.rd.idx))
[info] RegFileSpec:
[info] CheckerA
[info] - should pass *** FAILED ***
[info]   treadle.executable.TreadleException: setValue: Cannot find regFile1__GEN_8_invalid in symbol table
[info]   at treadle.executable.ExecutionEngine.$anonfun$setValue$1(ExecutionEngine.scala:279)
[info]   at scala.collection.MapLike.getOrElse(MapLike.scala:131)
[info]   at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
[info]   at scala.collection.AbstractMap.getOrElse(Map.scala:65)
[info]   at treadle.executable.SymbolTable.getOrElse(SymbolTable.scala:129)
[info]   at treadle.executable.ExecutionEngine.setValue(ExecutionEngine.scala:279)
[info]   at treadle.TreadleTester.poke(TreadleTester.scala:280)
[info]   at chiseltest.simulator.TreadleContext.poke(TreadleSimulator.scala:87)
[info]   at chiseltest.formal.backends.Trace$.$anonfun$replayOnSim$5(Trace.scala:27)
[info]   at chiseltest.formal.backends.Trace$.$anonfun$replayOnSim$5$adapted(Trace.scala:27)
[info]   ...
[info] CheckerB
[info] - should pass *** FAILED ***
[info]   chiseltest.formal.FailedBoundedCheckException: [CheckerB] found an assertion violation 0 steps after reset!
[info]   at chiseltest.formal.FailedBoundedCheckException$.apply(Formal.scala:26)
[info]   at chiseltest.formal.backends.Maltese$.bmc(Maltese.scala:66)
[info]   at chiseltest.formal.Formal$.executeOp(Formal.scala:82)
[info]   at chiseltest.formal.Formal$.$anonfun$verify$2(Formal.scala:62)
[info]   at chiseltest.formal.Formal$.$anonfun$verify$2$adapted(Formal.scala:62)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at chiseltest.formal.Formal$.verify(Formal.scala:62)
[info]   at chiseltest.formal.Formal.verify(Formal.scala:34)
[info]   at chiseltest.formal.Formal.verify$(Formal.scala:32)
[info]   at regfile.RegFileSpec.verify(RegFileSpec.scala:52)
[info]   ...
[info] Run completed in 3 seconds, 384 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
...
```

I noticed `treadle.executable.TreadleException` may caused by dead code elimination pass,
so I made `CheckerB` with a little different in structure.

### Steps to Reproduce

Get the code at [this commit](https://github.com/liuyic00/chisel-playground/commit/69f9050b63c9a82aca031af30c78cbb682aa78ba).

- run the test
  - `sbt test`

### My environment

- Chisel Verions: 3.5-SNAPSHOT
- chiseltest: 0.5-SNAPSHOT
- OS: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by ekiwi** [comment]
This should hopefully be fixed by #465 . In about 1h the latest snapshot release should contain the fix. Please feel free to re-open this issue if the problem persists.

Thanks for your detailed bug report!
