### ISSUE TITLE
Out of metaspace

### ISSUE THREAD

**Issue by nhynes** [ucb-bar/chisel-testers2#6]
I'm able to run `testOnly pkg.MyModuleSpec` in SBT about five times before getting an `OutOfMemoryError: Metaspace`. Based on removing parts of the (very simple) test, it seems like there's a memory leak per test run irrespective of what happens in the test (this is to say that it doesn't depend on whether there are peeks/pokes/steps).

I can only imagine that I'm doing something wrong...

Chisel version: `3.2-SNAPSHOT`
Scala version: `2.12.7`
SBT version: `1.0`

```
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:207)
[error] 	at sbt.Execute.next$1(Execute.scala:104)
[error] 	at sbt.Execute.processAll(Execute.scala:107)
[error] 	at sbt.Execute.runKeep(Execute.scala:84)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:387)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:386)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:405)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:100)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:331)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:98)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:174)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:387)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by ducky64** [comment]
Do you get the same issue when running other testers, like PeekPokeTester or the chisel3 regression suite? This pops up for me every once in a while (with the solution being restart sbt), so it might be a chisel3 or firrtl issue. If it's a chisel3 or firrtl issue, consider opening an issue in their respective repositories.

**Comment by nhynes** [comment]
I get this error every so often when using PeekPoke, but it only happens very rarely. There's probably a bug in chisel/firrtl, but testers2's usage of those package seems to make it more prone to this error.

**Comment by nhynes** [comment]
Trying again to use this library, but now with `SBT_OPTS="-XX:MaxMetaspaceSize=4096M"` which delays OOM for a reasonable while.

[Based on some `jmap` dumps](https://gist.github.com/nhynes/d64e6941fb642942c70f3ce3c36dbcfd), it looks like the culprit likely a bunch of interned `String` objects (i.e. definitely not class loading since that stays fairly constant). I wonder if it's not just the result of printing lines to console?
